### ISSUE TITLE
which pixelkit branch? podfile specifies local version

### ISSUE THREAD

**Issue by 8secz-johndpope** [hexagons/Luma-Face#1]
<img width="1138" alt="Screen Shot 2020-03-10 at 8 05 19 am" src="https://user-images.githubusercontent.com/50567111/76257498-e63b6700-62a5-11ea-8cee-2899acd376d8.png">

**Comment by heestand-xyz** [comment]
hey, sorry about that, it was `PixelKit 0.7.0`, fixed in latest commit!
